from __future__ import annotations

HAPP_ROUTING_HEADER = (
    "happ://routing/onadd/"
    "eyJOYW1lIjoiUlUgRGlyZWN0IiwiR2xvYmFsUHJveHkiOiJ0cnVlIiwiUmVtb3RlRE5TVHlwZSI6IkRvSCIs"
    "IlJlbW90ZUROU0RvbWFpbiI6Imh0dHBzOi8vY2xvdWRmbGFyZS1kbnMuY29tL2Rucy1xdWVyeSIs"
    "IlJlbW90ZUROU0lQIjoiMS4xLjEuMSIsIkRvbWVzdGljRE5TVHlwZSI6IkRvSCIsIkRvbWVzdGljRE5T"
    "RG9tYWluIjoiaHR0cHM6Ly9jb21tb24uZG90LmRucy55YW5kZXgubmV0L2Rucy1xdWVyeSIsIkRvbWVz"
    "dGljRE5TSVAiOiI3Ny44OC44LjgiLCJEaXJlY3RTaXRlcyI6WyJnZW9zaXRlOmNhdGVnb3J5LXJ1Iiwi"
    "ZG9tYWluOnZrLmNvbSIsImRvbWFpbjp2ay5ydSIsImRvbWFpbjp2a3ZpZGVvLnJ1IiwiZG9tYWluOm9r"
    "LnJ1IiwiZG9tYWluOm1haWwucnUiLCJkb21haW46Z29zdXNsdWdpLnJ1IiwiZG9tYWluOm1vcy5ydSIs"
    "ImRvbWFpbjpuYWxvZy5nb3YucnUiLCJkb21haW46c2JlcmJhbmsucnUiLCJkb21haW46c2Jlci5ydSIs"
    "ImRvbWFpbjp0YmFuay5ydSIsImRvbWFpbjp0aW5rb2ZmLnJ1IiwiZG9tYWluOnZ0Yi5ydSIsImRvbWFp"
    "bjphbGZhYmFuay5ydSIsImRvbWFpbjpnYXpwcm9tYmFuay5ydSIsImRvbWFpbjp5YW5kZXgucnUiLCJk"
    "b21haW46eWFuZGV4Lm5ldCIsImRvbWFpbjp5YS5ydSIsImRvbWFpbjpvem9uLnJ1IiwiZG9tYWluOndp"
    "bGRiZXJyaWVzLnJ1IiwiZG9tYWluOndob29zaC5iaWtlIiwiZG9tYWluOndob29zaC1iaWtlLnJ1Iiwi"
    "ZG9tYWluOmRhdGEud2hvb3NoLWJpa2UucnUiLCJnZW9zaXRlOnByaXZhdGUiXSwiRGlyZWN0SXAiOlsi"
    "Z2VvaXA6cnUiLCJnZW9pcDpwcml2YXRlIiwiMTAuMC4wLjAvOCIsIjE3Mi4xNi4wLjAvMTIiLCIxOTIu"
    "MTY4LjAuMC8xNiIsIjE2OS4yNTQuMC4wLzE2Il0sIkRvbWFpblN0cmF0ZWd5IjoiSVBJZk5vbk1hdGNo"
    "IiwiRmFrZUROUyI6ImZhbHNlIn0"
)


def caddyfile(panel_domain: str, sub_domain: str, cabinet_domain: str, api_domain: str, email: str) -> str:
    return f"""# Generated by blank-vpn-bot-installer.
{{
    email {email}
    servers {{
        protocols h1 h2 h3
    }}
}}

https://{panel_domain} {{
    encode zstd gzip
    reverse_proxy remnawave:3000 {{
        header_up X-Real-IP {{remote_host}}
        header_up Host {{host}}
    }}
    log {{
        output file /var/log/caddy/panel.log {{
            roll_size 30mb
            roll_keep 10
            roll_keep_for 720h
        }}
    }}
}}

https://{sub_domain} {{
    encode zstd gzip
    header {{
        Cache-Control "no-store, no-cache, must-revalidate, max-age=0"
        Pragma "no-cache"
        Expires "0"
        no-limit-xhttp-enabled 1
        no-limit-enabled 1
        noises-enable 1
        noises-type rand
        noises-packet 10-20
        noises-delay 10-16
        noises-applyto ipv4
        fragmentation-enable 1
        fragmentation-packets tlshello
        fragmentation-length 50-100
        fragmentation-interval 5
        fragmentation-maxsplit 100-200
        ping-type proxy
        check-url-via-proxy https://cp.cloudflare.com/generate_204
        routing "{HAPP_ROUTING_HEADER}"
    }}

    handle / {{
        respond "ok" 200
    }}

    handle /assets/* {{
        reverse_proxy remnawave-subscription-page:3010 {{
            header_up X-Real-IP {{remote_host}}
            header_up Host {{host}}
        }}
    }}

    handle {{
        reverse_proxy remnawave-subscription-page:3010 {{
            header_up X-Real-IP {{remote_host}}
            header_up Host {{host}}
        }}
    }}

    log {{
        output file /var/log/caddy/sub.log {{
            roll_size 30mb
            roll_keep 10
            roll_keep_for 720h
        }}
    }}
}}

https://{cabinet_domain} {{
    encode zstd gzip
    handle /api/* {{
        uri strip_prefix /api
        reverse_proxy remnawave_bot:8080
    }}
    handle {{
        reverse_proxy cabinet_frontend:80
    }}
}}

https://{api_domain} {{
    encode zstd gzip

    handle /health {{
        respond "ok" 200
    }}

    @bot_webhooks path /health/payment-webhooks /webhook /tribute-webhook /mulenpay-webhook /cryptobot-webhook /yookassa-webhook /wata-webhook /heleket-webhook /pal24-webhook /platega-webhook /cloudpayments-webhook /cloudpayments-webhook/check /cloudpayments-webhook/pay /cloudpayments-webhook/fail /freekassa-webhook /kassa-ai-webhook /riopay-webhook /severpay-webhook /paypear-webhook /rollypay-webhook /overpay-webhook /aurapay-webhook /remnawave-webhook
    handle @bot_webhooks {{
        reverse_proxy remnawave_bot:8080
    }}

    respond "" 404
}}

:443 {{
    tls internal
    respond 204
}}
"""


def landing_html(project_name: str) -> str:
    return f"""<!doctype html>
<html lang="ru">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{project_name}</title>
  <style>
    body {{ margin: 0; font-family: system-ui, -apple-system, Segoe UI, sans-serif; background: #10141f; color: #f6f7fb; }}
    main {{ min-height: 100vh; display: grid; place-items: center; padding: 32px; }}
    section {{ max-width: 720px; }}
    h1 {{ font-size: 36px; margin: 0 0 12px; }}
    p {{ color: #b7bfcc; line-height: 1.6; }}
  </style>
</head>
<body>
  <main>
    <section>
      <h1>{project_name}</h1>
      <p>Service is being configured.</p>
    </section>
  </main>
</body>
</html>
"""
