from __future__ import annotations

import base64
import json
from copy import deepcopy
from typing import Any


HAPP_ROUTING_CONFIG: dict[str, Any] = {
    "Name": "RU Direct",
    "GlobalProxy": "true",
    "RemoteDNSType": "DoH",
    "RemoteDNSDomain": "https://cloudflare-dns.com/dns-query",
    "RemoteDNSIP": "1.1.1.1",
    "DomesticDNSType": "DoH",
    "DomesticDNSDomain": "https://common.dot.dns.yandex.net/dns-query",
    "DomesticDNSIP": "77.88.8.8",
    "DirectSites": [
        "geosite:category-ru",
        "domain:vk.com",
        "domain:vk.ru",
        "domain:vkvideo.ru",
        "domain:ok.ru",
        "domain:mail.ru",
        "domain:gosuslugi.ru",
        "domain:mos.ru",
        "domain:nalog.gov.ru",
        "domain:sberbank.ru",
        "domain:sber.ru",
        "domain:tbank.ru",
        "domain:tinkoff.ru",
        "domain:vtb.ru",
        "domain:alfabank.ru",
        "domain:gazprombank.ru",
        "domain:yandex.ru",
        "domain:yandex.net",
        "domain:ya.ru",
        "domain:ozon.ru",
        "domain:wildberries.ru",
        "domain:whoosh.bike",
        "domain:whoosh-bike.ru",
        "domain:data.whoosh-bike.ru",
        "geosite:private",
    ],
    "DirectIp": [
        "geoip:ru",
        "geoip:private",
        "10.0.0.0/8",
        "172.16.0.0/12",
        "192.168.0.0/16",
        "169.254.0.0/16",
    ],
    "DomainStrategy": "IPIfNonMatch",
    "FakeDNS": "false",
}


def happ_routing_payload() -> dict[str, Any]:
    return deepcopy(HAPP_ROUTING_CONFIG)


def build_happ_routing_header(payload: dict[str, Any] | None = None) -> str:
    raw = json.dumps(payload or HAPP_ROUTING_CONFIG, ensure_ascii=False, separators=(",", ":")).encode("utf-8")
    encoded = base64.b64encode(raw).decode("ascii")
    return f"happ://routing/onadd/{encoded}"


HAPP_ROUTING_HEADER = build_happ_routing_header()


def caddyfile(panel_domain: str, sub_domain: str, cabinet_domain: str, api_domain: str, email: str) -> str:
    return f"""# Generated by blank-vpn-bot-installer.
{{
    email {email}
    servers {{
        protocols h1 h2 h3
    }}
}}

https://{panel_domain} {{
    encode zstd gzip
    reverse_proxy remnawave:3000 {{
        header_up X-Real-IP {{remote_host}}
        header_up Host {{host}}
    }}
    log {{
        output file /var/log/caddy/panel.log {{
            roll_size 30mb
            roll_keep 10
            roll_keep_for 720h
        }}
    }}
}}

https://{sub_domain} {{
    encode zstd gzip
    header {{
        Cache-Control "no-store, no-cache, must-revalidate, max-age=0"
        Pragma "no-cache"
        Expires "0"
        no-limit-enabled 1
        noises-enable 1
        noises-type rand
        noises-packet 10-20
        noises-delay 10-16
        noises-applyto ipv4
        fragmentation-enable 1
        fragmentation-packets tlshello
        fragmentation-length 50-100
        fragmentation-interval 5
        fragmentation-maxsplit 100-200
        ping-type proxy
        check-url-via-proxy https://cp.cloudflare.com/generate_204
        routing "{HAPP_ROUTING_HEADER}"
    }}

    handle / {{
        respond "ok" 200
    }}

    handle /assets/* {{
        reverse_proxy remnawave-subscription-page:3010 {{
            header_up X-Real-IP {{remote_host}}
            header_up Host {{host}}
            header_up X-Forwarded-Host {{host}}
            header_up X-Forwarded-Proto https
            header_up X-Forwarded-Ssl on
        }}
    }}

    handle {{
        reverse_proxy remnawave-subscription-page:3010 {{
            header_up X-Real-IP {{remote_host}}
            header_up Host {{host}}
            header_up X-Forwarded-Host {{host}}
            header_up X-Forwarded-Proto https
            header_up X-Forwarded-Ssl on
        }}
    }}

    log {{
        output file /var/log/caddy/sub.log {{
            roll_size 30mb
            roll_keep 10
            roll_keep_for 720h
        }}
    }}
}}

https://{cabinet_domain} {{
    encode zstd gzip
    handle /api/* {{
        uri strip_prefix /api
        reverse_proxy remnawave_bot:8080
    }}
    handle {{
        reverse_proxy cabinet_frontend:80
    }}
}}

https://{api_domain} {{
    encode zstd gzip

    handle /health {{
        respond "ok" 200
    }}

    @bot_webhooks path /health/payment-webhooks /webhook /tribute-webhook /mulenpay-webhook /cryptobot-webhook /yookassa-webhook /wata-webhook /heleket-webhook /pal24-webhook /platega-webhook /cloudpayments-webhook /cloudpayments-webhook/check /cloudpayments-webhook/pay /cloudpayments-webhook/fail /freekassa-webhook /kassa-ai-webhook /riopay-webhook /severpay-webhook /paypear-webhook /rollypay-webhook /overpay-webhook /aurapay-webhook /remnawave-webhook
    handle @bot_webhooks {{
        reverse_proxy remnawave_bot:8080
    }}

    respond "" 404
}}

:443 {{
    tls internal
    respond 204
}}
"""


def landing_html(project_name: str) -> str:
    return f"""<!doctype html>
<html lang="ru">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{project_name}</title>
  <style>
    body {{ margin: 0; font-family: system-ui, -apple-system, Segoe UI, sans-serif; background: #10141f; color: #f6f7fb; }}
    main {{ min-height: 100vh; display: grid; place-items: center; padding: 32px; }}
    section {{ max-width: 720px; }}
    h1 {{ font-size: 36px; margin: 0 0 12px; }}
    p {{ color: #b7bfcc; line-height: 1.6; }}
  </style>
</head>
<body>
  <main>
    <section>
      <h1>{project_name}</h1>
      <p>Service is being configured.</p>
    </section>
  </main>
</body>
</html>
"""
