"""Render local artifacts for Templar node bootstrap dry-runs."""

from __future__ import annotations

import json
from dataclasses import dataclass
from html import escape
from pathlib import Path

import yaml

from app.templar_node.schemas import NodeConfig, NodeRole, RealityStrategy, RealityTransport, TransitMode, WarpMode
from app.templar_node.secrets import LocalSecretStore


@dataclass(frozen=True)
class RenderedArtifact:
    relative_path: str
    content: str
    mode: str = '0644'


@dataclass(frozen=True)
class RenderedBundle:
    artifacts: tuple[RenderedArtifact, ...]

    def names(self) -> list[str]:
        return [artifact.relative_path for artifact in self.artifacts]


def render_bundle(config: NodeConfig, *, secret_store: LocalSecretStore | None = None) -> RenderedBundle:
    artifacts = [
        RenderedArtifact('opt/remnanode/.env', render_remnanode_env(config, secret_store), mode='0600'),
        RenderedArtifact('opt/remnanode/docker-compose.yml', render_remnanode_compose(config)),
        RenderedArtifact('etc/caddy/Caddyfile', render_caddyfile(config)),
        RenderedArtifact('opt/templar-node/ufw-plan.txt', render_ufw_plan(config)),
        RenderedArtifact('opt/templar-node/network-tuning.sh', render_network_tuning_script(config), mode='0755'),
        RenderedArtifact('etc/systemd/system/templar-node-network-tuning.service', render_network_tuning_service()),
        RenderedArtifact('opt/templar-node/xray-snippets.json', render_xray_snippets(config)),
    ]
    artifacts.extend(render_site_artifacts(config))
    return RenderedBundle(artifacts=tuple(artifacts))


def write_bundle(bundle: RenderedBundle, output_dir: str | Path) -> list[Path]:
    root = Path(output_dir)
    written: list[Path] = []
    for artifact in bundle.artifacts:
        path = root / artifact.relative_path
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(artifact.content, encoding='utf-8')
        path.chmod(int(artifact.mode, 8))
        written.append(path)
    return written


def render_remnanode_env(config: NodeConfig, secret_store: LocalSecretStore | None = None) -> str:
    secret_value = '<resolved-by-layer-1-from-secret-store>'
    if secret_store is not None:
        secret_value = secret_store.read_text(config.remnanode.secret_key_ref)

    lines = [
        '# Generated by templar-node. Do not commit real values.',
        f'NODE_PORT={config.remnanode.node_port}',
        f'XTLS_API_PORT={config.xray.xtls_api_port}',
        f'SECRET_KEY={secret_value}',
    ]
    return '\n'.join(lines) + '\n'


def render_remnanode_compose(config: NodeConfig) -> str:
    service = {
        'image': 'remnawave/node:latest',
        'container_name': config.display.internal_name.lower().replace('_', '-'),
        'restart': 'always',
        'network_mode': 'host',
        'env_file': '.env',
        'volumes': [
            './data:/var/lib/remnanode',
            './logs:/var/log/remnanode',
        ],
        'logging': {
            'driver': 'json-file',
            'options': {
                'max-size': '50m',
                'max-file': '5',
            },
        },
    }
    if config.warp.mode == WarpMode.XRAY_NATIVE:
        service['privileged'] = True
        service['cap_add'] = ['NET_ADMIN']
        service['devices'] = ['/dev/net/tun:/dev/net/tun']

    compose = {
        'services': {
            'remnanode': service,
        },
    }
    return yaml.safe_dump(compose, sort_keys=False)


def render_caddyfile(config: NodeConfig) -> str:
    if config.reality.strategy != RealityStrategy.LOCAL_DECOY_SITE:
        return '# remote_dest REALITY strategy: local Caddy decoy is not used.\n'

    cert_lines = _caddy_tls_lines(config)
    return f"""# Generated by templar-node for local REALITY decoy.
{{
\tservers {{
\t\tprotocols h1 h2
\t}}
}}

https://{config.domain}:{config.reality.local_decoy_port} {{
\tbind {config.reality.local_decoy_addr}
{cert_lines}
\troot * /opt/node-site/public
\tfile_server
\tencode zstd gzip
\theader {{
\t\t-Server
\t\tStrict-Transport-Security "max-age=15552000"
\t\tX-Content-Type-Options "nosniff"
\t\tReferrer-Policy "strict-origin-when-cross-origin"
\t}}
\ttry_files {{path}} {{path}}.html /index.html
\thandle_errors {{
\t\trewrite * /404.html
\t\tfile_server
\t}}
\tlog {{
\t\toutput file /var/log/caddy/node-decoy.log {{
\t\t\troll_size 30mb
\t\t\troll_keep 10
\t\t\troll_keep_for 720h
\t\t}}
\t}}
}}
"""


def render_site_artifacts(config: NodeConfig) -> list[RenderedArtifact]:
    if config.reality.strategy != RealityStrategy.LOCAL_DECOY_SITE:
        return []
    pages = _site_pages(config)
    return [
        RenderedArtifact('opt/node-site/public/index.html', pages['index']),
        RenderedArtifact('opt/node-site/public/about.html', pages['about']),
        RenderedArtifact('opt/node-site/public/contact.html', pages['contact']),
        RenderedArtifact('opt/node-site/public/privacy.html', pages['privacy']),
        RenderedArtifact('opt/node-site/public/404.html', pages['404']),
        RenderedArtifact('opt/node-site/public/robots.txt', _robots_txt()),
        RenderedArtifact('opt/node-site/public/favicon.svg', _favicon_svg(config)),
    ]


def render_ufw_plan(config: NodeConfig) -> str:
    lines = [
        '# Generated UFW plan. Apply with delayed rollback and active SSH session protection.',
        'ufw default deny incoming',
        'ufw default allow outgoing',
    ]
    for source in config.ssh.admin_allowlist:
        lines.append(f'ufw allow from {source} to any port {config.ssh.port} proto tcp comment "templar ssh allow-list"')
    lines.append(f'ufw allow {config.reality.public_port}/tcp comment "REALITY public inbound"')
    lines.append(f'ufw allow from {config.main_server.ipv4} to any port {config.remnanode.node_port} proto tcp comment "RemnaWave Node API"')
    if config.role == NodeRole.FOREIGN_EXIT and config.transit.mode == TransitMode.VLESS_REALITY:
        if config.host.inbound_ref == 'transit':
            lines.append(f'ufw allow {config.transit.listen_port}/tcp comment "VLESS transit direct fallback"')
        for source in config.transit.allow_from or []:
            lines.append(
                f'ufw allow from {source} to any port {config.transit.listen_port} proto tcp comment "VLESS transit from RU-edge"',
            )
    lines.append('ufw enable')
    return '\n'.join(lines) + '\n'


def render_network_tuning_script(config: NodeConfig) -> str:
    public_port = int(config.reality.public_port)
    return f"""#!/usr/bin/env bash
set -euo pipefail

REALITY_PUBLIC_PORT={public_port}
MSS_VALUE=1200
SYSCTL_FILE=/etc/sysctl.d/99-templar-node-mtu.conf

install -d -m 0755 /etc/sysctl.d
cat > "$SYSCTL_FILE" <<SYSCTL
net.ipv4.tcp_mtu_probing = 1
net.ipv4.tcp_ecn = 0
SYSCTL
sysctl -w net.ipv4.tcp_mtu_probing=1 >/dev/null
sysctl -w net.ipv4.tcp_ecn=0 >/dev/null

if command -v iptables >/dev/null 2>&1; then
  iptables -t mangle -C PREROUTING -p tcp --dport "$REALITY_PUBLIC_PORT" --tcp-flags SYN,RST SYN -j TCPMSS --set-mss "$MSS_VALUE" 2>/dev/null || \\
    iptables -t mangle -A PREROUTING -p tcp --dport "$REALITY_PUBLIC_PORT" --tcp-flags SYN,RST SYN -j TCPMSS --set-mss "$MSS_VALUE"
  iptables -t mangle -C OUTPUT -p tcp --sport "$REALITY_PUBLIC_PORT" --tcp-flags SYN,RST SYN -j TCPMSS --set-mss "$MSS_VALUE" 2>/dev/null || \\
    iptables -t mangle -A OUTPUT -p tcp --sport "$REALITY_PUBLIC_PORT" --tcp-flags SYN,RST SYN -j TCPMSS --set-mss "$MSS_VALUE"
fi
"""


def render_network_tuning_service() -> str:
    return """[Unit]
Description=Templar node TCP MSS and MTU tuning
After=network-online.target ufw.service
Wants=network-online.target
Before=docker.service

[Service]
Type=oneshot
ExecStart=/opt/templar-node/network-tuning.sh
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
"""


def render_xray_snippets(config: NodeConfig) -> str:
    snippets = {
        'role': config.role.value,
        'reality': _reality_snippet(config),
        'warp_outbound': _warp_snippet(config),
        'transit': _transit_snippet(config),
        'routing': _routing_snippet(config),
    }
    return json.dumps(snippets, ensure_ascii=False, indent=2, sort_keys=True) + '\n'


def _caddy_tls_lines(config: NodeConfig) -> str:
    if config.site.certificate_mode.value == 'file':
        return '\ttls /etc/caddy/certs/fullchain.pem /etc/caddy/certs/privkey.pem'
    if config.site.certificate_mode.value == 'http01':
        return '\ttls'
    return '\t# certificate_mode=dns01 requires custom Caddy DNS provider module\n\ttls'


def _site_pages(config: NodeConfig) -> dict[str, str]:
    title = escape(config.site.title)
    domain = escape(config.domain)
    contact = escape(config.site.contact_email)
    brand = title
    accent = _site_accent(config)
    tagline = _site_tagline(config)
    description = (
        f'{brand} is a small independent digital studio focused on practical web presence, '
        'content structure, landing pages, and lightweight product support.'
    )
    nav = _site_nav()
    footer = f'&copy; 2026 {brand}. Contact: <a href="mailto:{contact}">{contact}</a>'
    style = _site_css(accent)
    return {
        'index': _html_page(
            title=f'{brand} - Digital Studio',
            style=style,
            body=f"""
<header class="top">
  <a class="brand" href="/">{brand}</a>
  {nav}
</header>
<main>
  <section class="hero">
    <p class="eyebrow">{domain}</p>
    <h1>{tagline}</h1>
    <p>{description}</p>
  </section>
  <section class="grid">
    <article><h2>Web pages</h2><p>Compact websites, service pages, and product updates that stay simple to maintain.</p></article>
    <article><h2>Content care</h2><p>Clear page structure, editorial refreshes, and practical publishing support.</p></article>
    <article><h2>Small systems</h2><p>Lightweight forms, analytics checks, and deployment housekeeping for growing teams.</p></article>
  </section>
</main>
<footer>{footer}</footer>
""",
        ),
        'about': _html_page(
            title=f'About - {brand}',
            style=style,
            body=f"""
<header class="top">
  <a class="brand" href="/">{brand}</a>
  {nav}
</header>
<main class="narrow">
  <h1>About</h1>
  <p>{brand} works with small teams that need direct, low-maintenance digital materials without a large agency process.</p>
  <p>Projects are scoped around clear deliverables: a page, a launch checklist, a content update, or a small support cycle.</p>
</main>
<footer>{footer}</footer>
""",
        ),
        'contact': _html_page(
            title=f'Contact - {brand}',
            style=style,
            body=f"""
<header class="top">
  <a class="brand" href="/">{brand}</a>
  {nav}
</header>
<main class="narrow">
  <h1>Contact</h1>
  <p>For project notes, support requests, or availability questions, write to <a href="mailto:{contact}">{contact}</a>.</p>
  <p>Typical response time is one to two business days.</p>
</main>
<footer>{footer}</footer>
""",
        ),
        'privacy': _html_page(
            title=f'Privacy - {brand}',
            style=style,
            body=f"""
<header class="top">
  <a class="brand" href="/">{brand}</a>
  {nav}
</header>
<main class="narrow">
  <h1>Privacy</h1>
  <p>This website is intentionally minimal. Server logs may include request time, path, user agent, and network address for security and troubleshooting.</p>
  <p>No public account system, advertising profile, or newsletter tracking is operated on this site.</p>
</main>
<footer>{footer}</footer>
""",
        ),
        '404': _html_page(
            title=f'Not found - {brand}',
            style=style,
            body=f"""
<header class="top">
  <a class="brand" href="/">{brand}</a>
  {nav}
</header>
<main class="narrow">
  <h1>Page not found</h1>
  <p>The page may have moved or the address may be incomplete.</p>
  <p><a href="/">Return to the homepage</a></p>
</main>
<footer>{footer}</footer>
""",
        ),
    }


def _html_page(*, title: str, style: str, body: str) -> str:
    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{escape(title)}</title>
  <link rel="icon" href="/favicon.svg" type="image/svg+xml">
  <style>
{style}
  </style>
</head>
<body>
{body.strip()}
</body>
</html>
"""


def _site_nav() -> str:
    return '<nav><a href="/about">About</a><a href="/contact">Contact</a><a href="/privacy">Privacy</a></nav>'


def _site_css(accent: str) -> str:
    return f"""    :root {{ color-scheme: light; --accent: {accent}; --ink: #172026; --muted: #61717b; --line: #dfe7ea; --paper: #f7faf9; }}
    * {{ box-sizing: border-box; }}
    body {{ margin: 0; font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; color: var(--ink); background: var(--paper); line-height: 1.55; }}
    a {{ color: inherit; }}
    .top {{ display: flex; align-items: center; justify-content: space-between; gap: 24px; max-width: 1080px; margin: 0 auto; padding: 28px 24px; border-bottom: 1px solid var(--line); }}
    .brand {{ font-weight: 750; text-decoration: none; }}
    nav {{ display: flex; gap: 18px; flex-wrap: wrap; color: var(--muted); font-size: 14px; }}
    nav a {{ text-decoration: none; }}
    main {{ max-width: 1080px; margin: 0 auto; padding: 56px 24px 72px; }}
    .hero {{ max-width: 780px; }}
    .eyebrow {{ margin: 0 0 14px; color: var(--accent); font-weight: 700; font-size: 14px; text-transform: uppercase; letter-spacing: .08em; }}
    h1 {{ margin: 0 0 18px; font-size: clamp(36px, 7vw, 72px); line-height: .98; letter-spacing: 0; }}
    h2 {{ margin: 0 0 10px; font-size: 20px; letter-spacing: 0; }}
    p {{ max-width: 68ch; margin: 0 0 16px; color: var(--muted); }}
    .grid {{ display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 1px; margin-top: 56px; background: var(--line); border: 1px solid var(--line); }}
    article {{ min-height: 180px; padding: 24px; background: #fff; }}
    .narrow {{ max-width: 760px; }}
    footer {{ max-width: 1080px; margin: 0 auto; padding: 28px 24px 42px; border-top: 1px solid var(--line); color: var(--muted); font-size: 14px; }}
    @media (max-width: 760px) {{ .top {{ align-items: flex-start; flex-direction: column; }} .grid {{ grid-template-columns: 1fr; }} main {{ padding-top: 38px; }} }}"""


def _site_tagline(config: NodeConfig) -> str:
    choices = (
        'Clear digital work for practical teams.',
        'Small websites, useful systems, steady support.',
        'Simple web presence with careful maintenance.',
        'Focused digital pages for everyday operations.',
    )
    return choices[_stable_index(config.display.internal_name, len(choices))]


def _site_accent(config: NodeConfig) -> str:
    accents = ('#236b5f', '#315f72', '#725a31', '#663f5f', '#4d6743')
    return accents[_stable_index(config.domain, len(accents))]


def _favicon_svg(config: NodeConfig) -> str:
    accent = _site_accent(config)
    initial = escape(config.site.title.strip()[:1].upper() or 'D')
    return f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64">
  <rect width="64" height="64" rx="12" fill="{accent}"/>
  <text x="32" y="41" text-anchor="middle" font-family="Arial, sans-serif" font-size="30" font-weight="700" fill="#fff">{initial}</text>
</svg>
"""


def _robots_txt() -> str:
    return 'User-agent: *\nAllow: /\n'


def _stable_index(value: str, modulo: int) -> int:
    return sum(value.encode('utf-8')) % modulo


def _reality_snippet(config: NodeConfig) -> dict:
    snippet = {
        'strategy': config.reality.strategy.value,
        'public_port': config.reality.public_port,
        'flow': config.reality.flow,
        'serverNames': config.effective_reality_server_names(),
        'credentials_ref': config.reality.credentials_ref,
        'network': config.reality.transport.value,
        'security': 'reality',
        'realitySettings': '<filled-by-layer-2-from-secret-material>',
    }
    if config.reality.transport == RealityTransport.XHTTP:
        snippet['xhttpSettings'] = config.reality.xhttp.model_dump(mode='json') if config.reality.xhttp else None
    if config.reality.strategy == RealityStrategy.LOCAL_DECOY_SITE:
        snippet['dest'] = f'{config.reality.local_decoy_addr}:{config.reality.local_decoy_port}'
    else:
        snippet['dest'] = config.reality.target
    return snippet


def _warp_snippet(config: NodeConfig) -> dict | None:
    if config.warp.mode != WarpMode.XRAY_NATIVE:
        return None
    return {
        'tag': config.warp.outbound_tag,
        'protocol': 'wireguard',
        'settings': {
            'reserved': config.warp.reserved or '<computed-from-warp-registration-client-id>',
            'secret_ref': config.warp.registration_ref,
            'kernelMode': False,
            'mtu': 1280,
            'domainStrategy': 'ForceIPv4',
        },
    }


def _transit_snippet(config: NodeConfig) -> dict | None:
    if config.transit.mode != TransitMode.VLESS_REALITY:
        return None
    if config.role == NodeRole.FOREIGN_EXIT:
        return {
            'direction': 'inbound',
            'tag': config.transit.inbound_tag,
            'listen_port': config.transit.listen_port,
            'flow': config.transit.flow,
            'allow_from': config.transit.allow_from,
            'service_user': config.transit.service_user,
            'service_user_credential_ref': config.transit.service_user_credential_ref,
            'reality_credentials_ref': config.transit.reality_credentials_ref,
        }
    return {
        'direction': 'outbound',
        'tag': config.transit.outbound_tag,
        'foreign_exit': f'{config.transit.foreign_exit_domain}:{config.transit.foreign_exit_port}',
        'serverNames': config.transit.server_names,
        'service_user_credential_ref': config.transit.service_user_credential_ref,
        'reality_credentials_ref': config.transit.reality_credentials_ref,
        'backup_outbounds': [backup.model_dump(mode='json') for backup in config.transit.backup_outbounds],
    }


def _routing_snippet(config: NodeConfig) -> dict | None:
    if config.role != NodeRole.RU_EDGE or config.routing is None:
        return None
    return {
        'domainStrategy': 'IPIfNonMatch',
        'sniffing': {
            'enabled': True,
            'destOverride': ['http', 'tls', 'quic'],
            'routeOnly': True,
        },
        'rules_order': [
            'BLOCK private/bittorrent',
            'DNS resolver endpoint rules',
            'RU geo/site/allow-list direct',
            'PUBLIC_RU_INBOUND fallback to TRANSIT_TO_FOREIGN',
        ],
        'ru_dns': config.routing.ru_dns,
        'foreign_dns_via_transit': config.routing.foreign_dns_via_transit,
    }
